### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hmalmedal** [ajschumacher/rjstat#11]
It is time for a new release. The package has been updated to read and output version 2.0 of the JSON-stat format. If it is OK with you, I will upload under your name and then you will be sent a confirmation email which needs to be accepted.

**Comment by hmalmedal** [comment]
@ajschumacher Did you see this?

**Comment by ajschumacher** [comment]
Hi @hmalmedal! Seeing it now - sounds good! Thanks!

**Comment by hmalmedal** [comment]
Uploaded the package.

**Comment by ajschumacher** [comment]
Done! :+1:

**Comment by hmalmedal** [comment]
Already on CRAN. Excellent.

**Comment by ajschumacher** [comment]
Nice! I'll close this issue!
