### ISSUE TITLE
jsonstat objects

### ISSUE THREAD

**Issue by MansMeg** [ajschumacher/rjstat#13]
Hi!

Im starting to work with json-stat objects in R and I would like to be able to use lists in R to create a json-stat object in R that could be checked using the schema, to get meta data etc. Is there a reason why you only have implemented jsonstat.json -> data.frame in R instead of jsonstat.json -> rjsonstat -> data.frame?

I could contribute on this if you would be interested but that would affect the package api.

**Comment by ajschumacher** [comment]
Hmm; I think I have some idea what you mean but I'm not 100% sure. You're talking about an R-native representation of all of the json-stat spec? Maybe as an R object? Seems interesting to me, and I'm not sure it would necessarily require API changes (aside from additions). I would say try to put together what you're thinking and/or see what @hmalmedal thinks of it - he's much more the maintainer than I am.

**Comment by MansMeg** [comment]
Great!

Ill try to do this asap.

**Comment by MansMeg** [comment]
A first version can be found in PR1.
