### ISSUE TITLE
JSON-stat v1?

### ISSUE THREAD

**Issue by bobheff** [ajschumacher/rjstat#16]
I am trying to read data from the Irish Central Statistics Office, e.g.
http://www.cso.ie/StatbankServices/StatbankServices.svc/jsonservice/responseinstance/HPM02

Their files are, apparently, using version 1 of JSON-stat.  They're not alone in this (e.g. Statistics Sweden also use this format).  Apart from this, the files are valid.

I am having two issues: column headings are not being read correctly and rjstat complains that there is not a blank line at the end of the file.  For instance,

> library(rjstat)
> cso.url <- "http://www.cso.ie/StatbankServices/StatbankServices.svc/jsonservice/responseinstance/PEA01"
> df <- fromJSONstat(readLines(cso.url),naming="label")
Warning message:
In readLines(cso.url) :
  incomplete final line found on 'http://www.cso.ie/StatbankServices/StatbankServices.svc/jsonservice/responseinstance/PEA01'
> colnames(df)
NULL
> names(df)
[1] "Population Estimates (Persons in April)  by  Age Group, Sex and Year"

Is there any way to fix this?  The "final line" issue is not a big deal, but the column names issue is problematic.  I suspect the problem is that rjstat expects v2.0 of the format.

**Comment by hmalmedal** [comment]
For version 1 of JSON-stat rjstat gives a named list of one or more data frames. You need to select the correct list element. Also, you can drop `readLines`.

    library(rjstat)
    cso.url <- "http://www.cso.ie/StatbankServices/StatbankServices.svc/jsonservice/responseinstance/PEA01"
    cso.list <- fromJSONstat(cso.url)
    df <- cso.list[[1]]
    names(df)
    # [1] "Age Group" "Sex"       "Year"      "Statistic" "value"

**Comment by bobheff** [comment]
Thank you!
