### ISSUE TITLE
jsonstat package

### ISSUE THREAD

**Issue by zedoul** [ajschumacher/rjstat#17]
Hi,

I would like to share you that I created jsonstat package based on this implementation.

https://github.com/zedoul/jsonstat

I firstly tried to contribute instead but 1) it seems not under maintenance, 2) I thought it may take too long time to discuss like last year's one (https://github.com/ajschumacher/rjstat/issues/15) and 3) I want to implement tidyverse-like way of describing JSON-stat description not the rjstat way.

The jsonstat package supports full functionality of today's JSON-stat. And at least for now I would like to continue its maintenance.

Best regards,
Kim

**Comment by ajschumacher** [comment]
Hi!

I'm not sure why you think this package isn't under maintenance; I would describe it as stable, thanks to @hmalmedal's very good work. I also didn't see any pull requests after I encouraged you in #15.

Not a big deal though, and it is true that I personally don't think much about JSON-stat these days. Maybe your package is very cool!

I guess your package implements the idea from #15? I'll close this issue and note your package in #15 for people who would be interested.

Thanks!

**Comment by zedoul** [comment]
@ajschumacher true, it is stable :'DI rather meant that rjstat has not been updated for a while. Thank you for rjstat otherwise I cannot even think of using JSON-stat. :+1:

**Comment by badosa** [comment]
I don't see the point of having two similar (but different) JSON-stat packages for R.

@zedoul if rjstat has not been updated for a while, doesn't it make more sense to request a pull and enriched it with the new functionality?
