### ISSUE TITLE
appropriate PKGNAME-package \alias

### ISSUE THREAD

**Issue by ajschumacher** [ajschumacher/rjstat#22]
I got an email from Kurt Hornik on 2023-08-19:

---

Dear maintainer,

You have file 'rjstat/man/rjstat.Rd' with \docType{package}, likely
intended as a package overview help file, but without the appropriate
PKGNAME-package \alias as per "Documenting packages" in R-exts.

This seems to be the consequence of the breaking change

  Using @docType package no longer automatically adds a -package alias.
  Instead document _PACKAGE to get all the defaults for package
  documentation.

in roxygen2 7.0.0 (2019-11-12) having gone unnoticed, see
<https://github.com/r-lib/roxygen2/issues/1491>.

As explained in the issue, to get the desired PKGNAME-package \alias
back, you should either change to the new approach and document the new
special sentinel

  "_PACKAGE"

or manually add

  @aliases rjstat-package

if remaining with the old approach.

Please fix in your master sources as appropriate, and submit a fixed
version of your package within the next few months.

Best,
-k

---

@hmalmedal / @MansMeg can you address?

**Comment by hmalmedal** [comment]
@ajschumacher I made a fix and uploaded a new version to CRAN in your name. You will be sent an e-mail you must confirm.

**Comment by ajschumacher** [comment]
@hmalmedal confirmed! 👍👍👍

Also, do you want to take over maintainership officially? I haven’t really been doing anything here for some time; if you’re willing it seems like it would be more efficient to take me out of the loop… What do you think?

**Comment by hmalmedal** [comment]
I am willing to take over if that is what you want.

**Comment by ajschumacher** [comment]
I think it makes sense; I leave it to you! 😄
