### ISSUE TITLE
Feature request: support for R list objects

### ISSUE THREAD

**Issue by MarkPaulin** [ajschumacher/rjstat#23]
This package is great, I really appreciate the work that's gone into it and I would love to use it in my own work.

The API I'm working with is a bit odd in that it returns a JSON-stat object nested inside a larger JSON response. At the moment, I need to do something like this:

```
req <- httr2::request(some_url)
resp <- httr2::req_perform(req)
resp_body <- httr2::resp_body_json(resp)
jsonstat_list <- resp_body [["result"]]
jsonstat_text <- jsonlite::toJSON(jsonstat_list)
resp_data <- rjstat::fromJSONstat(jsonstat_text)
```

Would it make sense to skip the JSON to list conversion when a list is passed into `fromJSONstat()`? Or expose `parse_list()` or similar functionality?

Happy to submit a PR if you think this would be useful, but I appreciate it's a bit of a niche use-case.

**Comment by ajschumacher** [comment]
Hi! I hardly know, as I don't have this use case, but if you have an idea for a PR, I think it would be welcome! 👍

**Comment by MarkPaulin** [comment]
I've toyed around with this a little and I've had difficulties with the list I get from parsing the full response not matching the format expected by `parse_list()`. I think the solution would be to change how I handle the response object rather than parsing the entire thing.

I'm going to close this, thanks!

**Comment by ajschumacher** [comment]
Thanks for the update!

**Comment by badosa** [comment]
>  I think the solution would be to change how I handle the response object rather than parsing the entire thing.

I agree @MarkPaulin. I'm curious: Who is the provider of the API you mentioned? Could you provide an example? It's the first time I heard about an API that embeds a JSON-stat inside a larger JSON response.

**Comment by MarkPaulin** [comment]
The provider is CSO, the national statistics institute for Ireland (I work for NISRA who are using a carbon copy of the CSO API). Here's an example [response](https://ws.cso.ie/public/api.jsonrpc?data=%7B%22jsonrpc%22:%222.0%22,%22method%22:%22PxStat.Data.Cube_API.ReadDataset%22,%22params%22:%7B%22class%22:%22query%22,%22id%22:%5B%5D,%22dimension%22:%7B%7D,%22extension%22:%7B%22pivot%22:null,%22codes%22:false,%22language%22:%7B%22code%22:%22en%22%7D,%22format%22:%7B%22type%22:%22JSON-stat%22,%22version%22:%222.0%22%7D,%22matrix%22:%22BPA21%22%7D,%22version%22:%222.0%22%7D%7D).

I've realised since opening (and closing) this issue that they offer a separate API which doesn't wrap the JSON-stat inside another response, so I'm going to switch to using that (with rjstat!)

**Comment by badosa** [comment]
> I've realised since opening (and closing) this issue that they offer a separate API which doesn't wrap the JSON-stat inside another response

Exactly, Ireland's CSO supports different response flavors: the main one is 100% JSON-stat (they were early adopters of the format). That's why I was surprised: so far I'm not aware of any data provider embedding JSON-stat in a bigger JSON structure as the only type of API response.

Thanks for the clarification. I will soon add NISRA to the list of JSON-stat providers at https://json-stat.org/
