### ISSUE TITLE
new version of testthat

### ISSUE THREAD

**Issue by ajschumacher** [ajschumacher/rjstat#8]
Got this message from Hadley the other day:

> Hi all,
> 
> I'm planning to submit a new version of testthat to CRAN in two weeks
> (on May 19).
> 
> I've run R CMD check on all packages that use testhat, and if I
> noticed an error, I've sent you a bug report. However, there a lot of
> dependencies (>500!) so it's likely I've missed some problems. So
> please install the dev version of testthat
> (devtools::install_github("hadley/testthat")) and run R CMD check on
> your package.
> 
>Let me know if you have any problems!
> 
> Thanks,
> 
> Hadley

I imagine this won't be a problem but I thought I'd post it as an issue for visibility.

**Comment by hmalmedal** [comment]
I have checked it and it is OK.

**Comment by ajschumacher** [comment]
Thanks!
