### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hmalmedal** [ajschumacher/rjstat#9]
I have fixed some bugs lately. I think we should do a new release.

**Comment by ajschumacher** [comment]
Great! That sounds good. Do I need to do anything, or can you manage it? I'm okay with you doing whatever you think should be done. :+1:

**Comment by hmalmedal** [comment]
You need to answer the confirmation email.

**Comment by hmalmedal** [comment]
Submitted.

**Comment by ajschumacher** [comment]
Done! Thanks!

**Comment by ajschumacher** [comment]
Brian Ripley confirms it's on CRAN now! Good work!

**Comment by hmalmedal** [comment]
Excellent!
